"""
Embedding Classifier for production deployment.
Wraps OllamaEmbedder (HTTP) + sklearn RandomForest classifiers.

Embeddings are generated by calling Ollama's /api/embed endpoint over HTTP.
No GPU or PyTorch required in this container.
"""

import asyncio
import logging
import os
import pickle
import time
from pathlib import Path

import httpx
import numpy as np

from feature_extraction import extract_features

logger = logging.getLogger(__name__)

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")

# Cap concurrent /api/embed calls across all embedder instances. The CPU
# embedding backend on docker-ai has 4 worker slots; anything beyond that
# queues up and times out at the proxy's 120s ceiling. Default to 3 to leave
# one slot for other proxy clients (e.g. pve1).
_EMBED_CONCURRENCY = int(os.environ.get("OLLAMA_EMBED_CONCURRENCY", "3"))
_EMBED_SEMAPHORE = asyncio.Semaphore(_EMBED_CONCURRENCY)


class OllamaEmbedder:
    """Embedder that calls Ollama's /api/embed endpoint over HTTP."""

    # Retries are for real failures (proxy/upstream errors), not timeouts —
    # the 300s client timeout below covers slow embeds. Long-ish gaps let any
    # abandoned upstream work drain before we hit the worker pool again.
    _RETRY_ATTEMPTS = 3
    _RETRY_BACKOFF_SECONDS = [30, 90]

    def __init__(self, model_name: str, max_length: int = 2000, task_prefix: str = ""):
        self.model_name = model_name
        self.max_length = max_length
        self.task_prefix = task_prefix
        self._embedding_dim = 768
        # 300s matches the proxy's WriteTimeout. A single embed on CPU can
        # take ~120s under load; the previous 120s ceiling caused spurious
        # timeouts that triggered retries against a still-busy backend.
        self._client = httpx.AsyncClient(base_url=OLLAMA_BASE_URL, timeout=300.0)
        self._availability_cache: tuple[bool, float] | None = None
        self._availability_ttl = 900.0  # 15 minutes — models don't disappear quickly

    @property
    def embedding_dim(self) -> int:
        return self._embedding_dim

    async def is_available(self) -> bool:
        """Check if Ollama is reachable (cached for 15 minutes to avoid hammering the proxy)."""
        now = time.monotonic()
        if self._availability_cache is not None:
            cached_result, cached_at = self._availability_cache
            if now - cached_at < self._availability_ttl:
                return cached_result
        try:
            resp = await self._client.get("/api/tags")
            result = resp.status_code == 200
        except httpx.HTTPError:
            result = False
        self._availability_cache = (result, now)
        return result

    async def close(self):
        """Close the underlying HTTP client."""
        await self._client.aclose()

    async def encode(
        self,
        texts: list[str],
        show_progress_bar: bool = False,
        batch_size: int = 64,
    ) -> list[list[float]]:
        """Generate embeddings via Ollama /api/embed.

        Args:
            texts: List of texts to embed.
            show_progress_bar: Ignored (kept for interface compatibility).
            batch_size: Number of texts per Ollama request.

        Returns:
            List of embedding vectors (list of floats).

        Raises:
            httpx.HTTPError: After 3 retry attempts with exponential backoff.
        """
        prefixed = [f"{self.task_prefix}{t[:self.max_length]}" for t in texts]

        all_embeddings = []
        for i in range(0, len(prefixed), batch_size):
            batch = prefixed[i:i + batch_size]

            last_exc = None
            for attempt in range(self._RETRY_ATTEMPTS):
                try:
                    async with _EMBED_SEMAPHORE:
                        resp = await self._client.post(
                            "/api/embed",
                            json={"model": self.model_name, "input": batch, "truncate": True},
                        )
                    resp.raise_for_status()
                    data = resp.json()
                    all_embeddings.extend(data["embeddings"])
                    break
                except httpx.HTTPError as exc:
                    last_exc = exc
                    if attempt < self._RETRY_ATTEMPTS - 1:
                        backoff = self._RETRY_BACKOFF_SECONDS[attempt]
                        logger.warning(
                            f"Ollama request failed (attempt {attempt + 1}/{self._RETRY_ATTEMPTS}), "
                            f"retrying in {backoff}s: {type(exc).__name__}: {exc!r}"
                        )
                        await asyncio.sleep(backoff)
            else:
                raise last_exc

        return all_embeddings


class NomicV2Embedder(OllamaEmbedder):
    """
    Nomic Embed Text v2 MoE embedder via Ollama.
    768 dimensions, ~512 tokens, multilingual.
    Used for classification and general semantic search.
    """

    def __init__(self, max_length: int = 2000):
        super().__init__(
            model_name="nomic-embed-text-v2-moe",
            max_length=max_length,
            task_prefix="search_document: ",
        )


class ParaphraseEmbedder(OllamaEmbedder):
    """
    Paraphrase-multilingual-mpnet embedder via Ollama.
    768 dimensions, optimized for semantic similarity and duplicate detection.
    Better at identifying same-story articles with different wording.
    """

    def __init__(self, max_length: int = 2000):
        super().__init__(
            model_name="paraphrase-multilingual:278m-mpnet-base-v2-fp16",
            max_length=max_length,
            task_prefix="",
        )


class EmbeddingClassifier:
    """
    Production embedding classifier.
    Combines NomicV2 embeddings (via Ollama) with sklearn RandomForest.
    Supports both single-label and multi-label AK predictions.
    """

    # Classifier version info (updated when model is retrained)
    VERSION = "2.1.0"
    TRAINED_AT = "2026-01-13"
    TRAINING_ITEMS = 1680

    # Label mappings (integer class index to string label)
    PRIORITY_LABELS = ["high", "medium", "low"]
    AK_LABELS = ["AK1", "AK2", "AK3", "AK4", "AK5", "QAG"]

    def __init__(self):
        self.embedder = NomicV2Embedder()
        self.relevance_clf = None
        self.priority_clf = None
        self.ak_clf = None
        self.backend = "nomic-v2"
        self.multilabel = False  # Whether AK classifier is multi-label
        self.feature_scaler = None  # StandardScaler for geographic features
        self.feature_version = None
        self.relevance_threshold = 0.5  # Configurable threshold (from pkl or default)

    @classmethod
    def load(cls, model_path: str = "models/embedding_classifier_nomic-v2.pkl"):
        """Load trained classifier from pickle file."""
        instance = cls()

        path = Path(model_path)
        if not path.exists():
            raise FileNotFoundError(f"Model not found: {model_path}")

        with open(path, "rb") as f:
            data = pickle.load(f)

        # Handle dict format (both single-label and multi-label)
        if isinstance(data, dict):
            instance.relevance_clf = data["relevance_clf"]
            instance.priority_clf = data["priority_clf"]
            instance.ak_clf = data["ak_clf"]
            instance.backend = data.get("backend", "nomic-v2")
            instance.multilabel = data.get("multilabel", False)
            if instance.multilabel and "ak_classes" in data:
                instance.AK_LABELS = data["ak_classes"]
            # Load feature scaler (None if old model without features)
            instance.feature_scaler = data.get("feature_scaler")
            instance.feature_version = data.get("feature_version")
            instance.relevance_threshold = data.get("relevance_threshold", 0.5)
        else:
            # Legacy: class instance (shouldn't happen in production)
            instance.relevance_clf = data.relevance_clf
            instance.priority_clf = data.priority_clf
            instance.ak_clf = data.ak_clf
            instance.backend = getattr(data, "backend_name", "nomic-v2")
            instance.multilabel = hasattr(data, "ak_classes")
            if instance.multilabel:
                instance.AK_LABELS = data.ak_classes

        features_info = ""
        if instance.feature_scaler is not None:
            features_info = f", features=v{instance.feature_version}"
        logger.info(f"Loaded classifier: {instance.backend} (multilabel={instance.multilabel}{features_info})")
        return instance

    async def predict(
        self,
        title: str,
        content: str,
        source: str = "",
    ) -> dict:
        """
        Predict relevance, priority, and AK for a single item.

        Returns:
            dict with keys: relevant, relevance_confidence, priority,
                           priority_confidence, ak, ak_confidence,
                           aks (list), ak_confidences (dict) for multi-label
        """
        # Combine text fields (must match training format in data_loading.py)
        text = f"{title} {content}"
        if source:
            text += f" Quelle: {source}"

        # Get embedding
        X_emb = np.array(await self.embedder.encode([text], show_progress_bar=False))

        # Build full feature matrix (embeddings + geographic features)
        if self.feature_scaler is not None:
            features = extract_features(title, content, source).reshape(1, -1)
            features_scaled = self.feature_scaler.transform(features)
            X_full = np.hstack([X_emb, features_scaled])
        else:
            X_full = X_emb

        # Predict relevance (uses features for geographic rules)
        relevance_proba = self.relevance_clf.predict_proba(X_full)[0]
        relevant_idx = list(self.relevance_clf.classes_).index(1)
        relevance_confidence = relevance_proba[relevant_idx]
        is_relevant = relevance_confidence > self.relevance_threshold

        result = {
            "relevant": is_relevant,
            "relevance_confidence": float(relevance_confidence),
            "priority": None,
            "priority_confidence": None,
            "ak": None,
            "ak_confidence": None,
            "aks": [],
            "ak_confidences": {},
        }

        # Only predict priority/AK if relevant
        if is_relevant and self.priority_clf and self.ak_clf:
            # Priority (embeddings only — geographic features hurt priority)
            priority_proba = self.priority_clf.predict_proba(X_emb)[0]
            priority_idx = int(np.argmax(priority_proba))
            result["priority"] = self.PRIORITY_LABELS[priority_idx]
            result["priority_confidence"] = float(priority_proba[priority_idx])

            # AK prediction (uses features — source/geography helps topics)
            if self.multilabel:
                # Multi-label: predict multiple AKs
                ak_preds = self.ak_clf.predict(X_full)[0]
                ak_confidences = {}

                # Get probabilities for each AK
                predicted_aks = []
                for i, estimator in enumerate(self.ak_clf.estimators_):
                    prob = estimator.predict_proba(X_full)[0]
                    conf = prob[1] if len(prob) > 1 else prob[0]
                    ak_confidences[self.AK_LABELS[i]] = float(conf)
                    if ak_preds[i] == 1:
                        predicted_aks.append(self.AK_LABELS[i])

                # Fallback if no AK predicted
                if not predicted_aks:
                    best_idx = max(range(len(self.AK_LABELS)),
                                   key=lambda i: ak_confidences[self.AK_LABELS[i]])
                    predicted_aks = [self.AK_LABELS[best_idx]]

                result["aks"] = predicted_aks
                result["ak_confidences"] = ak_confidences
                # Primary AK for backward compatibility
                result["ak"] = predicted_aks[0] if predicted_aks else None
                result["ak_confidence"] = ak_confidences.get(result["ak"], 0.0)
            else:
                # Single-label: predict one AK
                ak_proba = self.ak_clf.predict_proba(X_full)[0]
                ak_idx = int(np.argmax(ak_proba))
                result["ak"] = self.AK_LABELS[ak_idx]
                result["ak_confidence"] = float(ak_proba[ak_idx])
                result["aks"] = [result["ak"]]
                result["ak_confidences"] = {result["ak"]: result["ak_confidence"]}

        return result

    async def get_info(self) -> dict:
        """Get classifier info."""
        ollama_available = await self.embedder.is_available()
        info = {
            "backend": self.backend,
            "embedding_dim": self.embedder.embedding_dim,
            "gpu_available": False,
            "gpu_name": None,
            "ollama_url": OLLAMA_BASE_URL,
            "ollama_available": ollama_available,
            "version": self.VERSION,
            "trained_at": self.TRAINED_AT,
            "training_items": self.TRAINING_ITEMS,
            "multilabel": self.multilabel,
        }
        info["relevance_threshold"] = self.relevance_threshold
        if self.feature_scaler is not None:
            info["feature_version"] = self.feature_version
            info["num_features"] = self.feature_scaler.n_features_in_
        return info


