"""
Embedding Classifier for production deployment.
Wraps OllamaEmbedder (HTTP) + sklearn RandomForest classifiers.
Includes VectorStore for semantic search and similarity.

Embeddings are generated by calling Ollama's /api/embed endpoint over HTTP.
No GPU or PyTorch required in this container.
"""

import asyncio
import logging
import os
import pickle
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import chromadb
from chromadb.config import Settings
import httpx
import numpy as np

from feature_extraction import extract_features

logger = logging.getLogger(__name__)

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")


class OllamaEmbedder:
    """Embedder that calls Ollama's /api/embed endpoint over HTTP."""

    _RETRY_ATTEMPTS = 3
    _RETRY_BACKOFF_SECONDS = [1, 2, 4]

    def __init__(self, model_name: str, max_length: int = 2000, task_prefix: str = ""):
        self.model_name = model_name
        self.max_length = max_length
        self.task_prefix = task_prefix
        self._embedding_dim = 768
        self._client = httpx.AsyncClient(base_url=OLLAMA_BASE_URL, timeout=120.0)
        self._availability_cache: tuple[bool, float] | None = None
        self._availability_ttl = 900.0  # 15 minutes — models don't disappear quickly

    @property
    def embedding_dim(self) -> int:
        return self._embedding_dim

    async def is_available(self) -> bool:
        """Check if Ollama is reachable (cached for 15 minutes to avoid hammering the proxy)."""
        now = time.monotonic()
        if self._availability_cache is not None:
            cached_result, cached_at = self._availability_cache
            if now - cached_at < self._availability_ttl:
                return cached_result
        try:
            resp = await self._client.get("/api/tags")
            result = resp.status_code == 200
        except httpx.HTTPError:
            result = False
        self._availability_cache = (result, now)
        return result

    async def close(self):
        """Close the underlying HTTP client."""
        await self._client.aclose()

    async def encode(
        self,
        texts: list[str],
        show_progress_bar: bool = False,
        batch_size: int = 64,
    ) -> list[list[float]]:
        """Generate embeddings via Ollama /api/embed.

        Args:
            texts: List of texts to embed.
            show_progress_bar: Ignored (kept for interface compatibility).
            batch_size: Number of texts per Ollama request.

        Returns:
            List of embedding vectors (list of floats).

        Raises:
            httpx.HTTPError: After 3 retry attempts with exponential backoff.
        """
        prefixed = [f"{self.task_prefix}{t[:self.max_length]}" for t in texts]

        all_embeddings = []
        for i in range(0, len(prefixed), batch_size):
            batch = prefixed[i:i + batch_size]

            last_exc = None
            for attempt in range(self._RETRY_ATTEMPTS):
                try:
                    resp = await self._client.post(
                        "/api/embed",
                        json={"model": self.model_name, "input": batch},
                    )
                    resp.raise_for_status()
                    data = resp.json()
                    all_embeddings.extend(data["embeddings"])
                    break
                except httpx.HTTPError as exc:
                    last_exc = exc
                    if attempt < self._RETRY_ATTEMPTS - 1:
                        backoff = self._RETRY_BACKOFF_SECONDS[attempt]
                        logger.warning(
                            f"Ollama request failed (attempt {attempt + 1}/{self._RETRY_ATTEMPTS}), "
                            f"retrying in {backoff}s: {exc}"
                        )
                        await asyncio.sleep(backoff)
            else:
                raise last_exc

        return all_embeddings


class NomicV2Embedder(OllamaEmbedder):
    """
    Nomic Embed Text v2 MoE embedder via Ollama.
    768 dimensions, ~512 tokens, multilingual.
    Used for classification and general semantic search.
    """

    def __init__(self, max_length: int = 2000):
        super().__init__(
            model_name="nomic-embed-text-v2-moe",
            max_length=max_length,
            task_prefix="search_document: ",
        )


class ParaphraseEmbedder(OllamaEmbedder):
    """
    Paraphrase-multilingual-mpnet embedder via Ollama.
    768 dimensions, optimized for semantic similarity and duplicate detection.
    Better at identifying same-story articles with different wording.
    """

    def __init__(self, max_length: int = 2000):
        super().__init__(
            model_name="paraphrase-multilingual:278m-mpnet-base-v2-fp16",
            max_length=max_length,
            task_prefix="",
        )


class EmbeddingClassifier:
    """
    Production embedding classifier.
    Combines NomicV2 embeddings (via Ollama) with sklearn RandomForest.
    Supports both single-label and multi-label AK predictions.
    """

    # Classifier version info (updated when model is retrained)
    VERSION = "2.1.0"
    TRAINED_AT = "2026-01-13"
    TRAINING_ITEMS = 1680

    # Label mappings (integer class index to string label)
    PRIORITY_LABELS = ["high", "medium", "low"]
    AK_LABELS = ["AK1", "AK2", "AK3", "AK4", "AK5", "QAG"]

    def __init__(self):
        self.embedder = NomicV2Embedder()
        self.relevance_clf = None
        self.priority_clf = None
        self.ak_clf = None
        self.backend = "nomic-v2"
        self.multilabel = False  # Whether AK classifier is multi-label
        self.feature_scaler = None  # StandardScaler for geographic features
        self.feature_version = None
        self.relevance_threshold = 0.5  # Configurable threshold (from pkl or default)

    @classmethod
    def load(cls, model_path: str = "models/embedding_classifier_nomic-v2.pkl"):
        """Load trained classifier from pickle file."""
        instance = cls()

        path = Path(model_path)
        if not path.exists():
            raise FileNotFoundError(f"Model not found: {model_path}")

        with open(path, "rb") as f:
            data = pickle.load(f)

        # Handle dict format (both single-label and multi-label)
        if isinstance(data, dict):
            instance.relevance_clf = data["relevance_clf"]
            instance.priority_clf = data["priority_clf"]
            instance.ak_clf = data["ak_clf"]
            instance.backend = data.get("backend", "nomic-v2")
            instance.multilabel = data.get("multilabel", False)
            if instance.multilabel and "ak_classes" in data:
                instance.AK_LABELS = data["ak_classes"]
            # Load feature scaler (None if old model without features)
            instance.feature_scaler = data.get("feature_scaler")
            instance.feature_version = data.get("feature_version")
            instance.relevance_threshold = data.get("relevance_threshold", 0.5)
        else:
            # Legacy: class instance (shouldn't happen in production)
            instance.relevance_clf = data.relevance_clf
            instance.priority_clf = data.priority_clf
            instance.ak_clf = data.ak_clf
            instance.backend = getattr(data, "backend_name", "nomic-v2")
            instance.multilabel = hasattr(data, "ak_classes")
            if instance.multilabel:
                instance.AK_LABELS = data.ak_classes

        features_info = ""
        if instance.feature_scaler is not None:
            features_info = f", features=v{instance.feature_version}"
        logger.info(f"Loaded classifier: {instance.backend} (multilabel={instance.multilabel}{features_info})")
        return instance

    async def predict(
        self,
        title: str,
        content: str,
        source: str = "",
    ) -> dict:
        """
        Predict relevance, priority, and AK for a single item.

        Returns:
            dict with keys: relevant, relevance_confidence, priority,
                           priority_confidence, ak, ak_confidence,
                           aks (list), ak_confidences (dict) for multi-label
        """
        # Combine text fields (must match training format in data_loading.py)
        text = f"{title} {content}"
        if source:
            text += f" Quelle: {source}"

        # Get embedding
        X_emb = np.array(await self.embedder.encode([text], show_progress_bar=False))

        # Build full feature matrix (embeddings + geographic features)
        if self.feature_scaler is not None:
            features = extract_features(title, content, source).reshape(1, -1)
            features_scaled = self.feature_scaler.transform(features)
            X_full = np.hstack([X_emb, features_scaled])
        else:
            X_full = X_emb

        # Predict relevance (uses features for geographic rules)
        relevance_proba = self.relevance_clf.predict_proba(X_full)[0]
        relevant_idx = list(self.relevance_clf.classes_).index(1)
        relevance_confidence = relevance_proba[relevant_idx]
        is_relevant = relevance_confidence > self.relevance_threshold

        result = {
            "relevant": is_relevant,
            "relevance_confidence": float(relevance_confidence),
            "priority": None,
            "priority_confidence": None,
            "ak": None,
            "ak_confidence": None,
            "aks": [],
            "ak_confidences": {},
        }

        # Only predict priority/AK if relevant
        if is_relevant and self.priority_clf and self.ak_clf:
            # Priority (embeddings only — geographic features hurt priority)
            priority_proba = self.priority_clf.predict_proba(X_emb)[0]
            priority_idx = int(np.argmax(priority_proba))
            result["priority"] = self.PRIORITY_LABELS[priority_idx]
            result["priority_confidence"] = float(priority_proba[priority_idx])

            # AK prediction (uses features — source/geography helps topics)
            if self.multilabel:
                # Multi-label: predict multiple AKs
                ak_preds = self.ak_clf.predict(X_full)[0]
                ak_confidences = {}

                # Get probabilities for each AK
                predicted_aks = []
                for i, estimator in enumerate(self.ak_clf.estimators_):
                    prob = estimator.predict_proba(X_full)[0]
                    conf = prob[1] if len(prob) > 1 else prob[0]
                    ak_confidences[self.AK_LABELS[i]] = float(conf)
                    if ak_preds[i] == 1:
                        predicted_aks.append(self.AK_LABELS[i])

                # Fallback if no AK predicted
                if not predicted_aks:
                    best_idx = max(range(len(self.AK_LABELS)),
                                   key=lambda i: ak_confidences[self.AK_LABELS[i]])
                    predicted_aks = [self.AK_LABELS[best_idx]]

                result["aks"] = predicted_aks
                result["ak_confidences"] = ak_confidences
                # Primary AK for backward compatibility
                result["ak"] = predicted_aks[0] if predicted_aks else None
                result["ak_confidence"] = ak_confidences.get(result["ak"], 0.0)
            else:
                # Single-label: predict one AK
                ak_proba = self.ak_clf.predict_proba(X_full)[0]
                ak_idx = int(np.argmax(ak_proba))
                result["ak"] = self.AK_LABELS[ak_idx]
                result["ak_confidence"] = float(ak_proba[ak_idx])
                result["aks"] = [result["ak"]]
                result["ak_confidences"] = {result["ak"]: result["ak_confidence"]}

        return result

    async def get_info(self) -> dict:
        """Get classifier info."""
        ollama_available = await self.embedder.is_available()
        info = {
            "backend": self.backend,
            "embedding_dim": self.embedder.embedding_dim,
            "gpu_available": False,
            "gpu_name": None,
            "ollama_url": OLLAMA_BASE_URL,
            "ollama_available": ollama_available,
            "version": self.VERSION,
            "trained_at": self.TRAINED_AT,
            "training_items": self.TRAINING_ITEMS,
            "multilabel": self.multilabel,
        }
        info["relevance_threshold"] = self.relevance_threshold
        if self.feature_scaler is not None:
            info["feature_version"] = self.feature_version
            info["num_features"] = self.feature_scaler.n_features_in_
        return info


class VectorStore:
    """
    ChromaDB-based vector store for semantic search and similarity.
    Uses the same NomicV2 embeddings as the classifier.
    """

    def __init__(self, embedder: NomicV2Embedder, persist_dir: str = "/app/data/vectordb"):
        """
        Initialize vector store.

        Args:
            embedder: NomicV2Embedder instance (shared with classifier)
            persist_dir: Directory for persistent storage
        """
        self.embedder = embedder
        self.persist_dir = persist_dir

        # Initialize ChromaDB with persistent storage
        Path(persist_dir).mkdir(parents=True, exist_ok=True)
        self.client = chromadb.PersistentClient(
            path=persist_dir,
            settings=Settings(anonymized_telemetry=False),
        )

        # Get or create collection
        self.collection = self.client.get_or_create_collection(
            name="news_items",
            metadata={"hnsw:space": "cosine"},
        )

        logger.info(f"VectorStore initialized: {self.collection.count()} items in collection")

    async def add_item(
        self,
        item_id: str,
        title: str,
        content: str,
        metadata: Optional[dict] = None,
    ) -> bool:
        """
        Add an item to the vector store (skips if already exists via upsert).

        Args:
            item_id: Unique identifier (e.g., database ID)
            title: Item title
            content: Item content
            metadata: Optional metadata (source, priority, ak, etc.)

        Returns:
            True if newly added, False if already existed
        """
        # Check if already exists (for return value only)
        existing = self.collection.get(ids=[item_id])
        already_exists = bool(existing["ids"])

        if already_exists:
            return False

        # Generate embedding
        text = f"{title} {content}"
        embedding = (await self.embedder.encode([text], show_progress_bar=False))[0]

        # Prepare metadata
        meta = metadata or {}
        meta["title"] = title[:500]  # Truncate for storage

        # Use upsert to avoid TOCTOU race between get and add
        self.collection.upsert(
            ids=[item_id],
            embeddings=[embedding],
            metadatas=[meta],
            documents=[text[:2000]],  # Store truncated text
        )

        return True

    async def add_items_batch(
        self,
        items: list[dict],
    ) -> int:
        """
        Add multiple items in batch.

        Args:
            items: List of dicts with keys: id, title, content, metadata (optional)

        Returns:
            Number of items added
        """
        # Filter out existing items
        ids = [str(item["id"]) for item in items]
        existing = set(self.collection.get(ids=ids)["ids"])
        new_items = [item for item in items if str(item["id"]) not in existing]

        if not new_items:
            return 0

        # Generate embeddings
        texts = [f"{item['title']} {item['content']}" for item in new_items]
        embeddings = await self.embedder.encode(texts, show_progress_bar=len(texts) > 10)

        # Prepare data
        ids = [str(item["id"]) for item in new_items]
        metadatas = []
        documents = []
        for idx, item in enumerate(new_items):
            meta = item.get("metadata", {}) or {}
            meta["title"] = item["title"][:500]
            # Filter out None values - ChromaDB doesn't accept them
            meta = {k: v for k, v in meta.items() if v is not None}
            metadatas.append(meta)
            documents.append(texts[idx][:2000])

        # Add to collection
        self.collection.add(
            ids=ids,
            embeddings=embeddings,
            metadatas=metadatas,
            documents=documents,
        )

        return len(new_items)

    async def search(
        self,
        query: str,
        n_results: int = 10,
        filter_metadata: Optional[dict] = None,
    ) -> list[dict]:
        """
        Semantic search for items matching a query.

        Args:
            query: Search query text
            n_results: Number of results to return
            filter_metadata: Optional filter (e.g., {"source": "hr"})

        Returns:
            List of results with id, title, score, metadata
        """
        # Generate query embedding
        embedding = (await self.embedder.encode([query], show_progress_bar=False))[0]

        # Search
        results = self.collection.query(
            query_embeddings=[embedding],
            n_results=n_results,
            where=filter_metadata,
            include=["metadatas", "documents", "distances"],
        )

        # Format results
        items = []
        for i in range(len(results["ids"][0])):
            items.append({
                "id": results["ids"][0][i],
                "title": results["metadatas"][0][i].get("title", ""),
                "score": 1 - results["distances"][0][i],  # Convert distance to similarity
                "metadata": results["metadatas"][0][i],
                "snippet": results["documents"][0][i][:300] if results["documents"] else "",
            })

        return items

    def find_similar(
        self,
        item_id: str,
        n_results: int = 5,
        exclude_same_source: bool = True,
    ) -> list[dict]:
        """
        Find items similar to a given item.

        Args:
            item_id: ID of the item to find similar items for
            n_results: Number of results to return
            exclude_same_source: Whether to exclude items from same source

        Returns:
            List of similar items with id, title, score, metadata
        """
        # Get the item's embedding
        item = self.collection.get(
            ids=[item_id],
            include=["embeddings", "metadatas"],
        )

        if not item["ids"]:
            return []

        embedding = item["embeddings"][0]
        item_source = item["metadatas"][0].get("source", "")

        # Search for similar (request extra to filter)
        results = self.collection.query(
            query_embeddings=[embedding],
            n_results=n_results + 10,  # Get extra for filtering
            include=["metadatas", "documents", "distances"],
        )

        # Format and filter results
        items = []
        for i in range(len(results["ids"][0])):
            result_id = results["ids"][0][i]

            # Skip the query item itself
            if result_id == item_id:
                continue

            # Optionally skip same source
            result_source = results["metadatas"][0][i].get("source", "")
            if exclude_same_source and result_source == item_source:
                continue

            items.append({
                "id": result_id,
                "title": results["metadatas"][0][i].get("title", ""),
                "score": 1 - results["distances"][0][i],
                "metadata": results["metadatas"][0][i],
                "snippet": results["documents"][0][i][:300] if results["documents"] else "",
            })

            if len(items) >= n_results:
                break

        return items

    def get_stats(self) -> dict:
        """Get vector store statistics."""
        return {
            "total_items": self.collection.count(),
            "persist_dir": self.persist_dir,
        }

    def get_all_items(self, batch_size: int = 1000) -> list[dict]:
        """Get all items from the vector store for syncing.

        Returns list of dicts with id, title, content (document).
        """
        total = self.collection.count()
        if total == 0:
            return []

        items = []
        offset = 0

        while offset < total:
            results = self.collection.get(
                limit=batch_size,
                offset=offset,
                include=["documents", "metadatas"],
            )

            for i, item_id in enumerate(results["ids"]):
                items.append({
                    "id": item_id,
                    "title": results["metadatas"][i].get("title", ""),
                    "content": results["documents"][i] if results["documents"] else "",
                    "metadata": results["metadatas"][i],
                })

            offset += batch_size

        return items


class DuplicateStore:
    """
    Separate vector store for duplicate detection using paraphrase embeddings.

    Uses paraphrase-multilingual-mpnet-base-v2 (via Ollama) which is optimized for
    semantic similarity - better at identifying same-story articles
    with different wording than the nomic model used for classification.

    Threshold recommendation: 0.75 for same-story detection.
    """

    def __init__(self, persist_dir: str = "/app/data/duplicatedb"):
        """
        Initialize duplicate store with its own paraphrase embedder.

        Args:
            persist_dir: Directory for persistent storage (separate from main vector store)
        """
        self.embedder = ParaphraseEmbedder()
        self.persist_dir = persist_dir

        # Initialize ChromaDB with persistent storage
        Path(persist_dir).mkdir(parents=True, exist_ok=True)
        self.client = chromadb.PersistentClient(
            path=persist_dir,
            settings=Settings(anonymized_telemetry=False),
        )

        # Separate collection for duplicate detection
        self.collection = self.client.get_or_create_collection(
            name="duplicate_detection",
            metadata={"hnsw:space": "cosine"},
        )

        logger.info(f"DuplicateStore initialized: {self.collection.count()} items in collection")

    @staticmethod
    def _normalize_fetched_at(meta: dict) -> dict:
        """Convert fetched_at ISO string to epoch float for ChromaDB filtering."""
        if "fetched_at" in meta and isinstance(meta["fetched_at"], str) and meta["fetched_at"]:
            try:
                dt = datetime.fromisoformat(meta["fetched_at"])
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                meta["fetched_at"] = dt.timestamp()
            except (ValueError, TypeError):
                del meta["fetched_at"]
        return meta

    async def add_item(
        self,
        item_id: str,
        title: str,
        content: str,
        metadata: Optional[dict] = None,
    ) -> bool:
        """Add an item to the duplicate store (skips if already exists via upsert)."""
        existing = self.collection.get(ids=[item_id])
        if existing["ids"]:
            return False

        text = f"{title} {content}"
        embedding = (await self.embedder.encode([text], show_progress_bar=False))[0]

        meta = metadata or {}
        meta["title"] = title[:500]
        meta = self._normalize_fetched_at(meta)

        # Use upsert to avoid TOCTOU race between get and add
        self.collection.upsert(
            ids=[item_id],
            embeddings=[embedding],
            metadatas=[meta],
            documents=[text[:2000]],
        )

        return True

    async def add_items_batch(self, items: list[dict]) -> int:
        """Add multiple items in batch."""
        ids = [str(item["id"]) for item in items]
        existing = set(self.collection.get(ids=ids)["ids"])
        new_items = [item for item in items if str(item["id"]) not in existing]

        if not new_items:
            return 0

        texts = [f"{item['title']} {item['content']}" for item in new_items]
        embeddings = await self.embedder.encode(texts, show_progress_bar=len(texts) > 10)

        ids = [str(item["id"]) for item in new_items]
        metadatas = []
        documents = []
        for idx, item in enumerate(new_items):
            meta = item.get("metadata", {}) or {}
            meta["title"] = item["title"][:500]
            meta = {k: v for k, v in meta.items() if v is not None}
            meta = self._normalize_fetched_at(meta)
            metadatas.append(meta)
            documents.append(texts[idx][:2000])

        self.collection.add(
            ids=ids,
            embeddings=embeddings,
            metadatas=metadatas,
            documents=documents,
        )

        return len(new_items)

    async def find_duplicates(
        self,
        title: str,
        content: str,
        threshold: float = 0.75,
        n_results: int = 5,
        fetched_after: str | None = None,
    ) -> list[dict]:
        """
        Find semantically similar items that may be duplicates.

        Uses paraphrase embeddings for better same-story detection.

        Args:
            title: Article title
            content: Article content
            threshold: Similarity threshold (default 0.75)
            n_results: Max results to return
            fetched_after: ISO timestamp - only match items fetched after this time

        Returns:
            List of duplicates with id, title, score, metadata
        """
        text = f"{title} {content}"
        embedding = (await self.embedder.encode([text], show_progress_bar=False))[0]

        # Build ChromaDB where filter for time-bounded dedup
        # ChromaDB requires numeric values for comparison operators
        where_filter = None
        if fetched_after:
            try:
                dt = datetime.fromisoformat(fetched_after)
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                where_filter = {"fetched_at": {"$gte": dt.timestamp()}}
            except (ValueError, TypeError):
                pass  # Skip filter if timestamp is unparseable

        query_kwargs = {
            "query_embeddings": [embedding],
            "n_results": n_results,
            "include": ["metadatas", "documents", "distances"],
        }
        if where_filter:
            query_kwargs["where"] = where_filter

        results = self.collection.query(**query_kwargs)

        items = []
        for i in range(len(results["ids"][0])):
            score = 1 - results["distances"][0][i]
            if score >= threshold:
                items.append({
                    "id": results["ids"][0][i],
                    "title": results["metadatas"][0][i].get("title", ""),
                    "score": score,
                    "metadata": results["metadatas"][0][i],
                    "snippet": results["documents"][0][i][:300] if results["documents"] else "",
                })

        return items

    async def get_stats(self) -> dict:
        """Get duplicate store statistics."""
        return {
            "total_items": self.collection.count(),
            "persist_dir": self.persist_dir,
            "model": self.embedder.model_name,
            "ollama_available": await self.embedder.is_available(),
        }
